### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MacAoi** [EC2854/Hyprland-Dots#1]
does the install script work

**Comment by EC2854** [comment]
It should work but i never tested it.

**Comment by vawwies** [comment]
Works just fine for me. Had it installed via the script a few days ago and three finger gesture was broken, seems to be fixed in the newest commit. Haven't run into any other issues yet.
![image](https://github.com/EC2854/Hyprland-Dots/assets/166329823/5656e2b0-6735-4485-8825-ee5e7a557c69)

**Comment by MacAoi** [comment]
[![2024-05-04-13-59-56-340.jpg](https://github.com/EC2854/Hyprland-Dots/assets/127881977/6f8bebe4-4f71-4746-bb33-b42bfebe7aea)
Well this problem arise for me what to do

**Comment by MacAoi** [comment]
![2024-05-04-13-59-56-340.jpg](https://github.com/EC2854/Hyprland-Dots/assets/127881977/9b8c191a-b2d0-4e67-aec8-d826ab52c131)

Well what to do now

**Comment by MacAoi** [comment]
I cloned your repo then excuted the install script

**Comment by EC2854** [comment]
install [paru](https://github.com/Morganamilo/paru) and run script again it should install packages

**Comment by MacAoi** [comment]
![2024-05-04-15-48-47-739.jpg](https://github.com/EC2854/Hyprland-Dots/assets/127881977/6bdb1f96-b754-4ca5-a875-987d56115d7a)

Help needed 😶‍🌫️

**Comment by EC2854** [comment]
try running `sudo systemctl enable --now sddm` to run wm, then open terminal (super+t) and run `hyprpm update -v; hyprpm remove Hyprspace; hyprpm add  https://github.com/KZDKM/Hyprspace`

**Comment by MacAoi** [comment]
![2024-05-04-16-22-42-853.jpg](https://github.com/EC2854/Hyprland-Dots/assets/127881977/c237d299-c616-452a-9793-ed33bb2b877b)

Sddm was not installed i installed it and header still not installing after hyprpm update

**Comment by MacAoi** [comment]
I searched for a bit and found you can solve headers not installing by installing cpio first then update it and headers are installed now what to do next other things are not loading like waybar wallpaper

**Comment by EC2854** [comment]
Rebooting may be helpful. for wallpaper press super+alt+w, for bar i use ags and not waybar and if it wont open on start try running `ags`.l

**Comment by MacAoi** [comment]
Nope wallpaper is not changing and when I use ags command it says it's already running

**Comment by EC2854** [comment]
then `killall ags; ags`  for wallpaper check if u have swww installed

**Comment by MacAoi** [comment]
Didn't do anything and yes swwe is installed

**Comment by MacAoi** [comment]
![2024-05-04-18-31-13-590.jpg](https://github.com/EC2854/Hyprland-Dots/assets/127881977/8808542d-e93e-4444-a070-2db5b68a4e6d)

And how to clear this error

**Comment by MacAoi** [comment]
![2024-05-04-18-32-18-290.jpg](https://github.com/EC2854/Hyprland-Dots/assets/127881977/b662a476-99c3-4eb7-9335-4eacfc9bdd52)

How to clear this error

**Comment by EC2854** [comment]
comment out or delete 170 line of ~/.config/hypr/keybinds.conf or install [Hyprspace plugin](https://github.com/KZDKM/Hyprspace)

**Comment by MacAoi** [comment]
You know what man I just try to clean install it man And Thanks for the help so far
