### ISSUE TITLE
changewall.sh does not change Nautilus's theming/icons

### ISSUE THREAD

**Issue by ghost** [EC2854/Hyprland-Dots#2]
Using the command SUPER + ALT + W, the script is able to change the background and border theming, but does not change Nautilus' icons or theme. 

https://github.com/EC2854/Hyprland-Dots/assets/166329823/b85b9d6b-c28e-48c3-b070-1a298516a695

(sorry for early issue submission, missclick ^^)

**Comment by EC2854** [comment]
it seems that sudo failed. try running it manually `~/.config/hypr/scripts/changewall.sh`. i have some issues with gtk 4 and it doesnt update instantly so check if it made link in ~/.config `ls -l ~/.config | grep gtk`

**Comment by vawwies** [comment]
ah, thanks for the nwg-look thing, i knew there was such a thing, just forgot what it was named. that fixed the icons issue.

seems like it did indeed make a link pointing to catppuccin mocha
``drwxr-xr-x 1 v v   24 May  4 18:01 gtk-3.0
lrwxrwxrwx 1 v v   62 May  4 18:01 gtk-4.0 -> /usr/share/themes/Catppuccin-Mocha-Standard-Mauve-Dark/gtk-4.0``

I've used the keybind for changing the wallpaper/colors because that seems to be more successful than manually executing it for whatever reason:
```
Setting Wallpaper to /home/v/Pictures/Wallpapers/background7.jpg
Extracting colors from /home/v/Pictures/Wallpapers/background7.jpg
convert: unable to open image '/root/Pictures/tmp_dont_look_at_it.jpg': No such file or directory @ error/blob.c/OpenBlob/3571.
convert: no images defined `txt:' @ error/convert.c/ConvertImageCommand/3362.
Picked most saturated color (#)
rm: cannot remove '/root/Pictures/tmp_dont_look_at_it.jpg': No such file or directory
Picked matching catppuccin color (red)
Changed border and trail colors
/home/v/.config/hypr/scripts/changewall.sh: line 101: /root/.config/hypr/border.conf: No such file or directory
Changed icon colors
Changed gtk 4 theme
Changed gtk 3 theme
rm: cannot remove '/root/.config/gtk-4.0'/home/v/.config/hypr/scripts/changewall.sh: line 119: /root/.config/ags/scss/_colors.scss: No such file or directory
: No such file or directory
ln: failed to create symbolic link '/root/.config/gtk-4.0': No such file or directory
awk: fatal: cannot open file `/root/.config/gtk-3.0/settings.ini' for reading: No such file or directory

(process:127837): dconf-WARNING **: 18:17:34.633: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=cf2e2c8b94c546439414918842dd35c5 --binary-syntax --close-stderr”: Child process exited with code 1
HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
Changed ags theme
sed: can't read /root/.config/gtk-3.0/settings.ini: No such file or directory

**Comment by EC2854** [comment]
if there is a symlink it should update the theme _soon_(if not try reloging).  for this output u gave it seems that part of the script was executed as root. If u ran it with sudo dont do that it should ask for password where it needs it.

**Comment by vawwies** [comment]
ah gotcha, ill keep that in mind. 
did it again without sudo and it ran just fine, a quick reboot after, the theme itself seems to be unchanged.
![image](https://github.com/EC2854/Hyprland-Dots/assets/166329823/71a3b177-9e4b-478e-b8c0-1848b4d3a530)

**Comment by EC2854** [comment]
maybe try `ls ~/.config/gtk-4.0` to check if theme even exists

**Comment by vawwies** [comment]
i do, its the catppuccin flavors from [catppuccin/gtk](https://github.com/catppuccin/gtk) that i installed before the dotfiles from my own quick yay grab (its just firefox, vesktop, steam, and the themes iirc)
![image](https://github.com/EC2854/Hyprland-Dots/assets/166329823/7cc26498-dc2b-4f6e-a21c-4430f1cdeab4)

**Comment by EC2854** [comment]
well i dont really know what the issue might be. maybe running nautilus as a command will tell something?

**Comment by vawwies** [comment]
ah, a few minutes later, looks like it finally came through. not sure what actually triggered it but, i guess its fixed now heh.
thanks~ been loving hyprland so far 
![image](https://github.com/EC2854/Hyprland-Dots/assets/166329823/f6b890a7-d212-42b9-a136-734dc7c5f436)
